app/src/main/assets/dashboard-amber-android-mobilejs-sdk.js, app/src/main/assets/dashboard-amber2-android-mobilejs-sdk.js
Fixing issue for rotation case on dashboard viewers
=> Fix: rotating dialog issue

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/SearchableActivity.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/repository/LibraryFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/repository/RepositoryFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/repository/fragment/ResourcesControllerFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/repository/fragment/SearchControllerFragment.java
Implementing prefTag property for resource controller
=> Fix: Repository view type no longer changes library section

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/repository/adapter/GridItemView.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/repository/adapter/ListItemView.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/repository/adapter/ResourceView.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/storage/adapter/FileAdapter.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/resource/viewbinder/FolderResourceBinder.java
http://jira.jaspersoft.com/browse/JM-1445. Get rid of date in LIST view
=> Get rid of date in LIST view

app/src/main/assets/dashboard-amber-android-mobilejs-sdk.js, app/src/main/assets/dashboard-amber2-android-mobilejs-sdk.js, app/src/main/assets/report-android-mobilejs-sdk.js
Update JS to consider window changes.
Fix for issue [JM-1379](http://jira.jaspersoft.com/browse/JM-1379)
=> Fix: Consider rotate event to update report scale

app/src/main/assets/dashboard-amber-android-mobilejs-sdk.js, app/src/main/assets/dashboard-amber2-android-mobilejs-sdk.js, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/viewer/html/dashboard/Amber2DashboardActivity.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/viewer/html/dashboard/AmberDashboardActivity.java, app/src/main/java/com/jaspersoft/android/jaspermobile/webview/dashboard/bridge/DashboardCallback.java, app/src/main/java/com/jaspersoft/android/jaspermobile/webview/dashboard/bridge/DashboardWebInterface.java
Add new method for `DashboardCallbacks#onAuthError`
=> Fix: Handle session expired case on Amber2 dashboards

app/src/main/assets/dashboard-amber2-android-mobilejs-sdk.js
Fix for issue [JM-1443](http://jira.jaspersoft.com/browse/JM-1443)
=> Fix: Broken hyperlink execution on Amber 2 dashboards

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/favorites/fragment/FavoritesControllerFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/favorites/fragment/FavoritesFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/ResourceOpener.java
Add new API for resource opener in order to path pref tag.
Fix for issue [JM-1451](http://jira.jaspersoft.com/browse/JM-1451).
=> Fix: Resolve view type switch case for favorites section

app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-zh/strings.xml, app/src/main/res/values/strings.xml
Task associated with issue [JM-1292](http://jira.jaspersoft.com/browse/JM-1292)
=> Task: Updating all languages

app/build.gradle, sdk/src/main/java/com/jaspersoft/android/retrofit/sdk/account/AccountServerData.java
Task associated with issue [JM-1483](http://jira.jaspersoft.com/browse/JM-1483)
=> Task: Updating username/password on phoneuser

app/src/main/assets/dashboard-amber-android-mobilejs-sdk.js, app/src/main/assets/dashboard-amber2-android-mobilejs-sdk.js, app/src/main/assets/report-android-mobilejs-sdk.js
Fix for issue [JM-1181](http://jira.jaspersoft.com/browse/JM-1181)
=> Fix: Render issue after maxiximze during pinch zoom

app/src/main/java/com/jaspersoft/android/jaspermobile/JasperMobileApplication.java, app/src/main/java/com/jaspersoft/android/jaspermobile/JasperMobileModule.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/auth/AuthenticatorFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/favorites/fragment/FavoritesFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/repository/fragment/ResourcesFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/auth/JasperAuthenticator.java, app/src/main/java/com/jaspersoft/android/jaspermobile/auth/JasperAuthenticatorService.java, app/src/main/java/com/jaspersoft/android/jaspermobile/legacy/JsServerProfileCompat.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/FavoritesHelper.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/ReportExecutionUtil.java, build.gradle, gradle/wrapper/gradle-wrapper.properties
Link issue [JM-200](http://jira.jaspersoft.com/browse/JM-200)
=> Epic: Adaptation of sdk 1.10

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/auth/AuthenticatorFragment.java
Jira issue [1503](http://jira.jaspersoft.com/browse/JM-1503)
=> Fix: Update error message response for servers lower than 5.2

app/src/main/assets/dashboard-amber-android-mobilejs-sdk.js, app/src/main/assets/dashboard-amber2-android-mobilejs-sdk.js, app/src/main/assets/report-android-mobilejs-sdk.js
Jira issue [1521](http://jira.jaspersoft.com/browse/JM-1521)
=> Updatings scripts with latest fixes.Add heartbeat fix.

app/src/main/java/com/jaspersoft/android/jaspermobile/network/ExceptionRule.java, app/src/main/java/com/jaspersoft/android/jaspermobile/network/RequestExceptionHandler.java, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-zh/strings.xml, app/src/main/res/values/strings.xml
Jira issue [1508](http://jira.jaspersoft.com/browse/JM-1508)
=> Fix: Change message generation odrder for network exceptions

app/build.gradle, app/src/androidTest/java/com/jaspersoft/android/jaspermobile/test/acceptance/save/SaveReportValidationsTest.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/favorites/fragment/FavoritesFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/library/fragment/LibraryFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/recent/fragment/RecentFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/repository/fragment/RepositoryFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/storage/fragment/SavedItemsFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/viewer/html/SavedReportHtmlViewerActivity.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/viewer/html/dashboard/BaseDashboardActivity.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/viewer/html/report/ReportViewerActivity.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/viewer/html/report/fragment/NodeWebViewFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/viewer/html/report/fragment/ReportActionFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/dialog/AboutDialogFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/dialog/NumberDialogFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/dialog/PageDialogFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/dialog/PasswordDialogFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/dialog/RenameDialogFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/network/RequestExceptionHandler.java, app/src/main/java/com/jaspersoft/android/jaspermobile/webview/SystemChromeClient.java, app/src/main/java/com/jaspersoft/android/jaspermobile/widget/MultiSelectSpinner.java, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-zh/strings.xml, app/src/main/res/values/strings.xml, version.properties
Jira issues:
* [JM-1492](http://jira.jaspersoft.com/browse/JM-1492)
* [JM-1498](http://jira.jaspersoft.com/browse/JM-1498)
* [JM-1499](http://jira.jaspersoft.com/browse/JM-1499)
* [JM-1584](http://jira.jaspersoft.com/browse/JM-1584)
=> Task: Update mising translations

app/src/main/assets/dashboard-amber-android-mobilejs-sdk.js, app/src/main/assets/dashboard-amber2-android-mobilejs-sdk.js, app/src/main/assets/report-android-mobilejs-sdk.js
Jira issue with [JM-1659](http://jira.jaspersoft.com/browse/JM-1659)
=> Fix: Attach resize listener after report loaded

app/src/main/java/com/jaspersoft/android/jaspermobile/auth/JasperAuthenticator.java, app/src/main/java/com/jaspersoft/android/jaspermobile/auth/JasperAuthenticatorService.java, app/src/main/java/com/jaspersoft/android/jaspermobile/dialog/PasswordDialogFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/network/RequestExceptionHandler.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/account/AccountServerData.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/server/ServerInfo.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/server/ServerInfoProvider.java, app/src/main/res/layout/dialog_password.xml, app/src/test/java/com/jaspersoft/android/jaspermobile/util/server/ServerInfoTest.java, version.properties
* Jira issue [JM-1520](http://jira.jaspersoft.com/browse/JM-1520)
* Jira issue [JM-1518](http://jira.jaspersoft.com/browse/JM-1518)
=> Fix: Password dialog flow

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/auth/AuthenticatorFragment.java, version.properties
Jira issue [JM-1690](http://jira.jaspersoft.com/browse/JM-1690)
=> Fix: Multiple login calls

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/library/fragment/LibraryFragment.java, version.properties
Jira issue [JM-1693](http://jira.jaspersoft.com/browse/JM-1693)
=> Fix: Crash library info dialog

app/src/main/java/com/jaspersoft/android/jaspermobile/webview/dashboard/bridge/DashboardWebInterface.java, app/src/main/java/com/jaspersoft/android/jaspermobile/webview/report/bridge/ReportWebInterface.java, version.properties
Jira issue [JM-1698](http://jira.jaspersoft.com/browse/JM-1698)
=> Fix: Unsubscribe window errors after load

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/repository/RepositorySearchableActivity.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/repository/fragment/RepositoryControllerFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/repository/fragment/RepositoryFragment.java, version.properties
Jira issue [JM-1700](http://jira.jaspersoft.com/browse/JM-1700)
=> Fix: Recursive search on repository

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/favorites/fragment/FavoritesFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/recent/fragment/RecentFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/repository/fragment/RepositoryFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/storage/fragment/SavedItemsFragment.java, version.properties
Jira issue [JM-1693](http://jira.jaspersoft.com/browse/JM-1693)
=> Fix: Crashes on info dialogs

app/src/main/assets/report-android-mobilejs-sdk.js, app/src/main/assets/report.html, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/viewer/html/report/ReportViewerActivity.java
Jira issues:
* [JM-1695](http://jira.jaspersoft.com/browse/JM-1695)
* [JM-1415](http://jira.jaspersoft.com/browse/JM-1415)
=> Fix: Update resize issue on rotate

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/viewer/html/report/ReportViewerActivity.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/VisualizeEndpoint.java, app/src/main/java/com/jaspersoft/android/jaspermobile/webview/dashboard/bridge/AmberTwoDashboardExecutor.java, app/src/test/java/com/jaspersoft/android/jaspermobile/util/VisualizeEndpointTest.java
- Add support for baseUrl      query
- Add support for optimized    query
- Add support for showControls query
=> Fix: Proxy issue for visualize resources

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/viewer/html/report/ReportViewerActivity.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/VisualizeEndpoint.java, app/src/main/java/com/jaspersoft/android/jaspermobile/webview/dashboard/bridge/AmberTwoDashboardExecutor.java, app/src/test/java/com/jaspersoft/android/jaspermobile/util/VisualizeEndpointTest.java
Reverts Jaspersoft/js-android-app#173
=> Revert "Revert "Fix: Proxy issue for visualize resources""

app/src/main/assets/dashboard-amber2-android-mobilejs-sdk.js, app/src/main/java/com/jaspersoft/android/jaspermobile/util/ScrollableTitleHelper.java, app/src/main/res/layout/scrollable_title_container.xml
Jira ISSUE [JM-1858](http://jira.jaspersoft.com/browse/JM-1858)
=> Fix: Refresh session issue

app/src/main/assets/dashboard-amber2-android-mobilejs-sdk.js
Jira ISSUE [JM-1858](http://jira.jaspersoft.com/browse/JM-1858)
=> Fix: Add missing callback for dashlet refresh

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/inputcontrols/InputControlsActivity.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/inputcontrols/adapters/InputControlsAdapter.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/inputcontrols/viewholders/BaseInputControlViewHolder.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/inputcontrols/viewholders/BooleanInputControlViewHolder.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/inputcontrols/viewholders/DateInputControlViewHolder.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/inputcontrols/viewholders/DateTimeInputControlViewHolder.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/inputcontrols/viewholders/NumberValueInputControlViewHolder.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/inputcontrols/viewholders/SelectInputControlViewHolder.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/inputcontrols/viewholders/TimeInputControlViewHolder.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/inputcontrols/viewholders/ValueInputControlViewHolder.java
Jira ISSUE [JM-1895](http://jira.jaspersoft.com/browse/JM-1895)
=> Feature: Show IC validation progress state

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/inputcontrols/InputControlsActivity.java
Jira ISSUE [JM-1917](http://jira.jaspersoft.com/browse/JM-1917)
=> Fix: Added ic values validation before saving report option

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/recent/fragment/RecentFragment.java
Jira ISSUE [JM-1865](http://jira.jaspersoft.com/browse/JM-1865)
=> Discard recently viewed selection after rotate

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/viewer/html/report/fragment/FilterManagerFragment.java, app/src/main/res/layout/view_simple_list.xml
Jira ISSUE [JM-1933](http://jira.jaspersoft.com/browse/JM-1933)
=> Fix: Fixed crash for pre lollipop devices. Fixed crash for REST reports.

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/inputcontrols/InputControlsActivity.java, app/src/main/res/layout/view_simple_list.xml
Jira ISSUE [JM-1929](http://jira.jaspersoft.com/browse/JM-1929)
=> Fix: Remove report options for CE

app/src/main/java/com/jaspersoft/android/jaspermobile/util/ResourceOpener.java, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml
Jira ISSUE [JM-1867](http://jira.jaspersoft.com/browse/JM-1867)
=> Fix: Open report and dashboards on any JRS 5.5+ server is available

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/settings/fragment/SettingsFragment.java, app/src/main/res/xml-v21/preferences.xml, app/src/main/res/xml/preferences.xml
Reverts Jaspersoft/js-android-app#212
=> Revert "Hide out session out resume option"

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/settings/fragment/SettingsFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/auth/JasperAuthenticator.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/DefaultPrefHelper.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/account/JasperAccountManager.java, app/src/main/res/values/strings.xml, app/src/main/res/xml-v21/preferences.xml, app/src/main/res/xml/preferences.xml
Reverts Jaspersoft/js-android-app#203
=> Revert "Feature: Optional Session Refresh"

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/save/fragment/SaveItemFragment.java
Jira ISSUE [JM-1811](http://jira.jaspersoft.com/browse/JM-1811)
=> Fix: Unable user to save report with name that already used for shared saved items

app/src/main/java/com/jaspersoft/android/jaspermobile/dialog/SaveReportOptionDialogFragment.java
Jira ISSUE [JM-1935](http://jira.jaspersoft.com/browse/JM-1935)
=> Fix: Trimming report option name while saving

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/favorites/fragment/FavoritesFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/library/fragment/LibraryFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/recent/fragment/RecentFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/repository/fragment/RepositoryFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/storage/fragment/SavedItemsFragment.java, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml
Jira issue [JM-1940](http://jira.jaspersoft.com/browse/JM-1940)
=> FIx: Generifying error for missing resources

app/src/main/res/values/strings.xml
Jira ISSUE [JM-1943](http://jira.jaspersoft.com/browse/JM-1943)
=> Fix: Updated input controls titles

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/favorites/FavoritesPageFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/favorites/fragment/FavoritesControllerFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/favorites/fragment/FavoritesFragment.java
Jira ISSUE [JM-1941](http://jira.jaspersoft.com/browse/JM-1941)
=> Fix: Sorting reset on reenter favorite page

app/src/main/java/com/jaspersoft/android/jaspermobile/util/ResourceOpener.java
Jira issue [JM-1947](http://jira.jaspersoft.com/browse/JM-1947)
=> Fix: Incorrect condition for Dashboard opening

app/src/main/java/com/jaspersoft/android/jaspermobile/auth/JasperAuthenticator.java
Jira ISSUE [JM-1952](http://jira.jaspersoft.com/browse/JM-1952)
=> Fix: Fixed problem with update to 2.2 with enabled always ask password option

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/favorites/fragment/FavoritesFragment.java
Jira ISSUE [JM-1951](http://jira.jaspersoft.com/browse/JM-1951)
=> Fix: Hide sort button after searching

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/inputcontrols/viewholders/BooleanInputControlViewHolder.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/inputcontrols/viewholders/DateTimeInputControlViewHolder.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/inputcontrols/viewholders/ValueInputControlViewHolder.java
Jira ISSUE [JM-1956](http://jira.jaspersoft.com/browse/JM-1956)
=> Fix: Disable input control if it has "read-only" property

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/inputcontrols/viewholders/BooleanInputControlViewHolder.java
Jira ISSUE [JM-1955](http://jira.jaspersoft.com/browse/JM-1955)
=> Fix: Show star symbol near mandatory boolean IC

app/src/main/res/layout-land/add_account_layout.xml, app/src/main/res/layout-sw600dp-land/add_account_layout.xml, app/src/main/res/layout-sw600dp/add_account_layout.xml, app/src/main/res/layout/add_account_layout.xml
Jira ISSUE [JM-1939](http://jira.jaspersoft.com/browse/JM-1939)
=> Fix: Added scroll for auth page

README.md, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml, version.properties
=> Feature: Updating branding strings

app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml
Jira ISSUE [JM-1892](http://jira.jaspersoft.com/browse/JM-1892)
=> Feature: Added link to What's new in about section

app/src/main/java/com/jaspersoft/android/jaspermobile/util/JsSpiceManager.java
Jira issue [JM-1980](http://jira.jaspersoft.com/browse/JM-1980)
=> Fix: Verify rest client valid before performing call

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/save/fragment/SaveItemFragment.java, app/src/main/res/values/strings.xml, build.gradle
Jira issue [JM-1877](http://jira.jaspersoft.com/browse/JM-1877)
=> Feature: Marshmallow permissions

app/src/main/java/com/jaspersoft/android/jaspermobile/util/filtering/RepositoryResourceFilter.java
Jira issue [JM-1990](http://jira.jaspersoft.com/browse/JM-1990)
=> Feature: All resources is visible in repository

app/src/main/AndroidManifest.xml, app/src/main/java/com/jaspersoft/android/jaspermobile/JasperMobileApplication.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/file/FileOpenFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/file/FileViewerActivity.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/ResourceOpener.java, app/src/main/res/layout/activity_file_viewer.xml, app/src/main/res/layout/fragment_file_open.xml, app/src/main/res/values/strings.xml
Jira issue [JM-1993](http://jira.jaspersoft.com/browse/JM-1993)
=> Feature: open new resources

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/file/ExternalOpenFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/file/ImageFileViewFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/ResourceOpener.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/filtering/FavoritesResourceFilter.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/filtering/JasperResources.java, app/src/main/res/layout/fragment_file_open.xml, app/src/main/res/values/strings.xml
Jira issue [JM-2012](http://jira.jaspersoft.com/browse/JM-2012)
=> Fix: Show all files in favorites

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/file/FileLoadFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/settings/fragment/SettingsFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/DefaultPrefHelper.java, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml-v21/preferences.xml, app/src/main/res/xml/preferences.xml
Jira issue [JM-2013](http://jira.jaspersoft.com/browse/JM-2013)
=> Feature: resources cache manager

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/file/FileViewerActivity.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/file/UnsupportedFilesFragment.java, app/src/main/res/layout/fragment_unsupported_file.xml
Jira issue [JM-2027](http://jira.jaspersoft.com/browse/JM-2027)
=> Fix: Fixed problem with empty page on opening unsupported files

app/src/main/AndroidManifest.xml, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/navigation/NavigationActivity.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/save/SaveReportService.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/save/fragment/SaveItemFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/storage/adapter/FileAdapter.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/storage/fragment/SavedItemsFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/SavedItemHelper.java, app/src/main/res/values/strings.xml, database-generator/schema/jasper.json
Jira issue [JM-2033](http://jira.jaspersoft.com/browse/JM-2033)
=> Feauture: move saving to service

app/src/main/res/drawable-v21/bg_info_btn.xml, app/src/main/res/drawable-v21/bg_resource_item.xml, app/src/main/res/drawable/bg_info_btn.xml, app/src/main/res/layout/item_resource_grid.xml, app/src/main/res/layout/item_resource_list.xml
Jira issue [JM-2019](http://jira.jaspersoft.com/browse/JM-2019)
=> Feature: Updated resources click effect.

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/repository/fragment/RepositoryFragment.java
Jira issue [JM-2035](http://jira.jaspersoft.com/browse/JM-2035)
=> Fix: public folder label

app/src/main/java/com/jaspersoft/android/jaspermobile/util/resource/viewbinder/FileResourceBinder.java
Jira issue [JM-2055](http://jira.jaspersoft.com/browse/JM-2055)
=> Fix: Added missed RFT file icon

app/src/main/java/com/jaspersoft/android/jaspermobile/util/filtering/FavoritesResourceFilter.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/filtering/JasperResources.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/filtering/RepositoryResourceFilter.java
Jira issue [JM-2037](http://jira.jaspersoft.com/browse/JM-2037)
=> Fix: Fixed repo and favorites filter to show supported files only

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/save/SaveReportService.java
Jira issue [JM-1212](http://jira.jaspersoft.com/browse/JM-1212)
=> Fix: Fixed problem with saving huge reports

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/save/SaveReportService.java
Jira issue [JM-1353](http://jira.jaspersoft.com/browse/JM-1353)
=> Fix: Fixed problem with incorrect count of saving reports

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/save/SaveReportService.java
Jira issue [JM-1289](http://jira.jaspersoft.com/browse/JM-1289)
=> Fix: Fixed problem with saving report attachments

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/save/SaveReportService.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/save/fragment/SaveItemFragment.java
Jira issue [JM-2060](http://jira.jaspersoft.com/browse/JM-2060)
=> Fix: Fixed problem with saving report with different params

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/repository/fragment/RepositoryFragment.java, build.gradle
Jira issue [JM-2072](http://jira.jaspersoft.com/browse/JM-2072)
=> Fix: Fixed problem with showing folders in top of repo

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/info/SimpleInfoFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/resource/viewbinder/JasperResourceConverter.java, build.gradle
Jira issue [JM-2073](http://jira.jaspersoft.com/browse/JM-2073)
=> Fix: Fixed problem with empty info fields

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/save/SaveReportService.java
Jira issue [JM-1212](http://jira.jaspersoft.com/browse/JM-1212)
=> Fix: Retry report exporting again if it failes while saving 

app/src/main/res/values/strings.xml
Jira issue [JM-2080](http://jira.jaspersoft.com/browse/JM-2080)
=> Fix: Fixed about dialog text links

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/save/SaveReportService.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/storage/adapter/FileAdapter.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/resource/viewbinder/ResourceView.java, app/src/main/java/com/jaspersoft/android/jaspermobile/widget/GridItemView.java, app/src/main/java/com/jaspersoft/android/jaspermobile/widget/ListItemView.java, app/src/main/res/drawable/bg_cancel_saving.xml, app/src/main/res/layout/res_grid_item.xml, app/src/main/res/layout/res_list_item.xml
Jira issue [JM-1288](http://jira.jaspersoft.com/browse/JM-1288)
=> Feature: cancel saving report

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/file/FileLoadFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/file/HtmlFileViewFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/repository/fragment/RepositoryFragment.java, app/src/main/res/layout/fragment_html_open.xml
Jira issue [JM-2077](http://jira.jaspersoft.com/browse/JM-2077)
=> Fix: html attachments session expired

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/favorites/fragment/FavoritesFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/storage/fragment/SavedItemsFragment.java
Jira issue [JM-2071](http://jira.jaspersoft.com/browse/JM-2071)
=> Fix: Fixed crash on favorite and saved items because of null analytic

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/favorites/fragment/FavoritesFragment.java
Jira issue [JM-2081](http://jira.jaspersoft.com/browse/JM-2081)
=> Fix: empty favorite back

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/favorites/fragment/FavoritesFragment.java
Additional fixes for https://github.com/Jaspersoft/js-android-app/pull/300
=> Fix: Fixed problem with account switching on favorites

app/src/main/assets/report-android-mobilejs-sdk.js, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/viewer/html/report/ReportViewerActivity.java, app/src/main/java/com/jaspersoft/android/jaspermobile/dialog/ProgressDialogFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/webview/report/bridge/ReportCallback.java, app/src/main/java/com/jaspersoft/android/jaspermobile/webview/report/bridge/ReportWebInterface.java, app/src/main/res/layout/activity_report_viewer.xml
Jira issue [JM-2087](http://jira.jaspersoft.com/browse/JM-2087)
=> Fixed endless progress dialog showing while report running

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/info/fragments/ResourceInfoFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/info/fragments/SavedItemInfoFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/widget/InfoView.java, app/src/main/res/values/strings.xml
Jira issue [JM-2089](http://jira.jaspersoft.com/browse/JM-2089)
=> Feature: Added version and user access fields for info page

app/build.gradle, app/src/main/java/com/jaspersoft/android/jaspermobile/db/JSDatabaseHelper.java, app/src/main/java/com/jaspersoft/android/jaspermobile/db/migrate/Migration.java, app/src/main/java/com/jaspersoft/android/jaspermobile/db/migrate/MigrationV2.java, app/src/main/java/com/jaspersoft/android/jaspermobile/db/migrate/MigrationV3.java, app/src/main/java/com/jaspersoft/android/jaspermobile/db/migrate/MigrationV4.java, app/src/main/java/com/jaspersoft/android/jaspermobile/db/migrate/MigrationV5.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/account/JasperAccountManager.java, app/src/test/java/com/jaspersoft/android/jaspermobile/db/migrate/FavoriteTableColumnsMigrationV3Test.java, app/src/test/java/com/jaspersoft/android/jaspermobile/db/migrate/FavoritesMigrationV3Test.java, app/src/test/java/com/jaspersoft/android/jaspermobile/db/migrate/LegacyProfileMigrationV3Test.java, app/src/test/java/com/jaspersoft/android/jaspermobile/db/migrate/MigrationV4Test.java, app/src/test/java/com/jaspersoft/android/jaspermobile/db/migrate/MigrationV5Test.java, app/src/test/java/com/jaspersoft/android/jaspermobile/db/migrate/ProfilesToAccountsMigrationV3Test.java, app/src/test/java/com/jaspersoft/android/jaspermobile/db/migrate/SavedItemsMigrationV3Test.java, app/src/test/java/com/jaspersoft/android/jaspermobile/db/migrate/ShadowApplicationImpl.java, database-generator/schema/jasper.json, version.properties
Fix token invalidation during intercept event
Add explicit migration to invalidate tokens
Incapsulate migrations inside migrate package
Incrementing version 2.2.2.004 -> 2.2.2.005
=> Fix: Invalidation issue with migartion refactor

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/inputcontrols/InputControlsActivity.java
Jira Issue [JM-2120](http://jira.jaspersoft.com/browse/JM-2120)
=> FIx: Report option label is case sensitive now

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/library/fragment/LibraryFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/repository/fragment/RepositoryFragment.java
Jira Issue [JM-2124](http://jira.jaspersoft.com/browse/JM-2124)
=> Fix: Fixed problem with incorrect view type switching while refreshing

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/favorites/FavoritesPageFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/favorites/fragment/FavoritesFragment.java
Jira Issue [JM-2125](http://jira.jaspersoft.com/browse/JM-2125)
=> Fix: Sort type on favorites is saved after recreate

app/src/main/java/com/jaspersoft/android/jaspermobile/util/feedback/Message.java, app/src/main/res/values/constants.xml
Jira Issue [JM-2126](http://jira.jaspersoft.com/browse/JM-2126)
=> Added app version name to feedback in pair with version code

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/auth/AuthenticatorFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/dialog/ProgressDialogFragment.java
Jira Issue [JM-2118](http://jira.jaspersoft.com/browse/JM-2118)
=> Fix: Progress bar now shows correctly after rotation

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/viewer/html/dashboard/BaseDashboardActivity.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/viewer/html/report/ReportViewerActivity.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/viewer/html/report/fragment/NodeWebViewFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/cookie/CookieManagerFactory.java, app/src/main/java/com/jaspersoft/android/jaspermobile/cookie/JsCookieManager.java, app/src/main/java/com/jaspersoft/android/jaspermobile/cookie/LegacyCookieManager.java, app/src/main/java/com/jaspersoft/android/jaspermobile/cookie/LollipopCookieManager.java
Jira Issue [JM-2119](http://jira.jaspersoft.com/browse/JM-2119)
Jira Issue [JM-2123](http://jira.jaspersoft.com/browse/JM-2123)
=> Fix: Fixed problem with refreshing cookies for webviews

app/src/main/java/com/jaspersoft/android/jaspermobile/auth/JasperAuthenticator.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/account/JasperAccountManager.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/security/PasswordManager.java
Jira Issue [JM-2130](http://jira.jaspersoft.com/browse/JM-2130)
=> Fix: Password manager is singleton now

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/navigation/NavigationActivity.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/robospice/RoboCastActivity.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/viewer/html/report/ReportCastActivity.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/viewer/html/report/ReportViewerActivity.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/ResourceOpener.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/cast/ReportCastHelper.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/cast/ReportPresentation.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/cast/ReportPresentationService.java, app/src/main/res/layout/activity_cast_report.xml, app/src/main/res/layout/report_presentation.xml, app/src/main/res/menu/cast_menu.xml, app/src/main/res/menu/retrofit_report_menu.xml, app/src/main/res/menu/sort_menu.xml, app/src/main/res/values/constants.xml, app/src/main/res/values/strings.xml
Jira Issue [JM-2117](http://jira.jaspersoft.com/browse/JM-2117)
=> Feature: Translation adapter

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/robospice/RoboCastActivity.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/viewer/html/report/ReportCastActivity.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/ScreenUtil.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/cast/ReportPresentation.java, app/src/main/java/com/jaspersoft/android/jaspermobile/widget/ScrollComputableWebView.java, app/src/main/res/layout/activity_cast_report.xml, app/src/main/res/layout/report_presentation.xml, app/src/main/res/menu-v19/cast_menu.xml
Jira Issue [JM-2116](http://jira.jaspersoft.com/browse/JM-2116)
=> Feature: Cast reports

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/viewer/html/dashboard/Amber2DashboardActivity.java
Jira Issue [JM-2133](http://jira.jaspersoft.com/browse/JM-2133)
=> Fix: Fixed dashboard label on auth error

app/src/main/assets/report_cast.html, app/src/main/java/com/jaspersoft/android/jaspermobile/util/ScreenUtil.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/cast/ResourcePresentationService.java
Jira Issue [JM-2153](http://jira.jaspersoft.com/browse/JM-2153)
=> Fix: Fixed problem with report scale while casting

app/src/main/AndroidManifest.xml, app/src/main/java/com/jaspersoft/android/jaspermobile/Analytics.java, app/src/main/java/com/jaspersoft/android/jaspermobile/JasperMobileApplication.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/file/FileViewerActivity.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/info/ResourceInfoActivity.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/info/fragments/ReportInfoFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/info/fragments/SimpleInfoFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/library/LibraryPageFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/library/fragment/LibraryFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/navigation/NavigationActivity.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/robospice/RoboToolbarActivity.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/save/SaveReportService.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/viewer/html/report/ReportCastActivity.java, app/src/main/java/com/jaspersoft/android/jaspermobile/dialog/ReportOptionsFragmentDialog.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/FavoritesHelper.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/account/AccountServerData.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/account/JasperAccountManager.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/cast/ResourcePresentationService.java, app/src/main/res/values/constants.xml
Jira Issue [JM-2180](http://jira.jaspersoft.com/browse/JM-219-)
=> Feature: Added analytic for 2.3 epics

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/save/fragment/SaveItemFragment.java
Jira Issue [JM-2190](http://jira.jaspersoft.com/browse/JM-2190)
=> Fix: Fixed crash while saving report on marshmallow

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/save/fragment/SaveItemFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/SavedItemHelper.java
Jira Issue [JM-2191](http://jira.jaspersoft.com/browse/JM-2191)
=> Fix: save report with same name

app/src/main/java/com/jaspersoft/android/jaspermobile/JasperMobileApplication.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/SavedItemHelper.java
Jira Issue [JM-2192](http://jira.jaspersoft.com/browse/JM-2192)
=> Fix: Remove unsaved file on app start

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/info/fragments/ReportInfoFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/dialog/ReportOptionsFragmentDialog.java
Jira Issue [JM-2194](http://jira.jaspersoft.com/browse/JM-2194)
=> Fix: Hide report option button for report without saved values

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/info/fragments/ResourceInfoFragment.java
Jira Issue [JM-2223](http://jira.jaspersoft.com/browse/JM-2223)
=> Fix: Fixed crash on adding to favorites from info

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/viewer/html/report/fragment/FilterManagerFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/dialog/ReportOptionsFragmentDialog.java
Jira Issue [JM-2222](http://jira.jaspersoft.com/browse/JM-2222)
=> Fix: Fixed problem with running report with report options from info

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/schedule/ScheduleActivity.java, app/src/main/java/com/jaspersoft/android/jaspermobile/dialog/OutputFormatDialogFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/dialog/ValueInputDialogFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/JobOutputFormatConverter.java, app/src/main/res/values/strings.xml
Jira issue [JM-2301](http://jira.jaspersoft.com/browse/JM-2301)
Jira issue [JM-2300](http://jira.jaspersoft.com/browse/JM-2300)
Jira issue [JM-2303](http://jira.jaspersoft.com/browse/JM-2303)
Jira issue [JM-2305](http://jira.jaspersoft.com/browse/JM-2305)
Jira issue [JM-2306](http://jira.jaspersoft.com/browse/JM-2306)
Jira issue [JM-2308](http://jira.jaspersoft.com/browse/JM-2308)
Jira issue [JM-2307](http://jira.jaspersoft.com/browse/JM-2307)
=> Fix: Fixed job strings

app/build.gradle, app/src/main/java/com/jaspersoft/android/jaspermobile/JasperMobileApplication.java
Jira issue [JM-2281](http://jira.jaspersoft.com/browse/JM-2281)
=> Fix: Removed multidex. Enabled build script.

app/src/main/AndroidManifest.xml, app/src/main/java/com/jaspersoft/android/jaspermobile/Analytics.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/info/fragments/ReportInfoFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/schedule/EditScheduleActivity.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/schedule/JobsFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/schedule/NewScheduleActivity.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/schedule/ScheduleFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/dialog/OutputFormatDialogFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/internal/di/components/ProfileComponent.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/JobOutputFormatConverter.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/resource/viewbinder/JasperResourceConverter.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/resource/viewbinder/JobResourceBinder.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/schedule/JobConverter.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/schedule/ScheduleViewModel.java, app/src/main/res/menu/report_edit_schedule.xml, app/src/main/res/values/strings.xml
Jira issue [JM-2177](http://jira.jaspersoft.com/browse/JM-2177)
=> Feature: job edit

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/save/ReportDownloadManager.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/save/SaveReportService.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/save/fragment/SaveItemFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/storage/fragment/SavedItemsFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/viewer/html/WebViewFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/internal/di/components/ProfileComponent.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/SavedItemHelper.java, app/src/main/res/values/strings.xml
Jira issue [JM-2209](http://jira.jaspersoft.com/browse/JM-2209)
Jira issue [JM-2311](http://jira.jaspersoft.com/browse/JM-2311)
Jira issue [JM-2312](http://jira.jaspersoft.com/browse/JM-2312)
Jira issue [JM-2309](http://jira.jaspersoft.com/browse/JM-2309)
=> Fix: Replaced IntentService with Service for saving report

app/src/main/res/values/strings.xml
Jira issue [JM-2301](http://jira.jaspersoft.com/browse/JM-2301)
=> Fix: Fixed empty jobs list label.

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/library/fragment/LibraryFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/repository/fragment/RepositoryFragment.java
Jira issue [JM-2323](http://jira.jaspersoft.com/browse/JM-2323)
=> Fix: Fixed "loadNext" event for analytic

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/file/ExternalOpenFragment.java
Jira issue [JM-2304](http://jira.jaspersoft.com/browse/JM-2304)
=> Fix: Removed checking supported apps for opening file

app/src/main/java/com/jaspersoft/android/jaspermobile/dialog/ReportOptionsFragmentDialog.java, app/src/main/java/com/jaspersoft/android/jaspermobile/dialog/SortDialogFragment.java, app/src/main/res/values-v21/themes.xml, app/src/main/res/values/styles.xml, app/src/main/res/values/themes.xml
Jira issue [JM-2314](http://jira.jaspersoft.com/browse/JM-2314)
=> Fix: Fixed problem with preLollipop sort dialog color

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/schedule/NewScheduleActivity.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/schedule/JobConverter.java
Jira issue [JM-2335](http://jira.jaspersoft.com/browse/JM-2335)
=> Fix: Now job can not be scheduled without selecting output formats

app/src/main/java/com/jaspersoft/android/jaspermobile/network/RequestExceptionHandler.java, app/src/main/res/values/strings.xml
Jira issue [JM-2333](http://jira.jaspersoft.com/browse/JM-2333)
Jira issue [JM-2334](http://jira.jaspersoft.com/browse/JM-2334)
Jira issue [JM-2337](http://jira.jaspersoft.com/browse/JM-2337)
=> Fix: Fixed schedule error messages

app/src/main/java/com/jaspersoft/android/jaspermobile/util/ControllerFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/DefaultPrefHelper.java, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml-v21/preferences.xml, app/src/main/res/xml/preferences.xml
Jira issue [JM-2350](http://jira.jaspersoft.com/browse/JM-2350)
=> Fix: Removed animation setting

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/library/LibraryPageFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/DefaultPrefHelper.java, app/src/main/res/values/strings.xml
Jira issue [JM-2348](http://jira.jaspersoft.com/browse/JM-2348)
=> Fix: Added voice help dialog

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/info/fragments/SavedItemInfoFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/schedule/JobsFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/viewer/html/SavedReportHtmlViewerActivity.java, app/src/main/java/com/jaspersoft/android/jaspermobile/dialog/DeleteDialogFragment.java, app/src/main/res/values/strings.xml
Jira issue [JM-2347](http://jira.jaspersoft.com/browse/JM-2347)
=> Feature: Added job cancel confirm dialog

app/src/main/java/com/jaspersoft/android/jaspermobile/presentation/view/fragment/ReportViewFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/presentation/view/fragment/ReportVisualizeFragment.java
Jira issue [JM-2347](http://jira.jaspersoft.com/browse/JM-2347)
=> Feature: Added schedule button for report viewers

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/schedule/ScheduleFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/widget/DateTimeView.java, app/src/main/res/values/strings.xml
Jira issue [JM-2336](http://jira.jaspersoft.com/browse/JM-2336)
Jira issue [JM-2349](http://jira.jaspersoft.com/browse/JM-2349)
=> Fix: Fixed problem with empty or past schedule date

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/library/fragment/LibraryFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/repository/fragment/RepositoryFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/data/repository/resource/InMemoryResourceRepository.java, app/src/main/java/com/jaspersoft/android/jaspermobile/domain/interactor/resource/SearchResourcesCase.java
Jira issue [JM-2316](http://jira.jaspersoft.com/browse/JM-2316)
=> Fix: Fixed problem with loading resources for library and repository

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/viewer/html/report/ReportCastActivity.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/cast/ResourceCastDialog.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/cast/ResourcePresentationService.java
Jira issue [JM-2198](http://jira.jaspersoft.com/browse/JM-2198)
=> Fis: Fixed problem while casting empty report

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/info/fragments/ReportInfoFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/save/ReportDownloadManager.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/save/fragment/SaveItemFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/data/entity/ExportBundle.java
Jira issue [JM-2330](http://jira.jaspersoft.com/browse/JM-2330)
=> Fix: Fixed problem with saving multi page report from info page

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/save/SaveReportService.java, app/src/main/java/com/jaspersoft/android/jaspermobile/dialog/PasswordDialogFragment.java
Jira issue [JM-2316](http://jira.jaspersoft.com/browse/JM-2316)
Jira issue [JM-2353](http://jira.jaspersoft.com/browse/JM-2353)
Jira issue [JM-2331](http://jira.jaspersoft.com/browse/JM-2331)
=> Fix: Fixed start intent for saving/password restoration

app/src/main/java/com/jaspersoft/android/jaspermobile/util/resource/viewbinder/CustomBitmapProcessor.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/resource/viewbinder/ReportResourceBinder.java
Jira issue [JM-2366](http://jira.jaspersoft.com/browse/JM-2366)
=> Fix: Handle negative width/height for original thumbnail

app/src/main/java/com/jaspersoft/android/jaspermobile/presentation/contract/RestReportContract.java, app/src/main/java/com/jaspersoft/android/jaspermobile/presentation/presenter/ReportViewPresenter.java, app/src/main/java/com/jaspersoft/android/jaspermobile/presentation/presenter/ReportVisualizePresenter.java, app/src/main/java/com/jaspersoft/android/jaspermobile/presentation/view/fragment/ReportViewFragment.java
Jira issue [JM-2329](http://jira.jaspersoft.com/browse/JM-2329)
=> Fix: Handle 500+ http codes for rest/vis viewers

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/repository/fragment/RepositoryFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/schedule/EditScheduleActivity.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/schedule/NewScheduleActivity.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/schedule/ScheduleFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/dialog/ValueInputDialogFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/resource/viewbinder/JobResourceBinder.java, app/src/main/res/layout/fragment_schedule.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/themes.xml
Jira issue [JM-2351](http://jira.jaspersoft.com/browse/JM-2351)
Jira issue [JM-2356](http://jira.jaspersoft.com/browse/JM-2356)
Jira issue [JM-2324](http://jira.jaspersoft.com/browse/JM-2324)
Jira issue [JM-2325](http://jira.jaspersoft.com/browse/JM-2325)
Jira issue [JM-2326](http://jira.jaspersoft.com/browse/JM-2326)
Jira issue [JM-2341](http://jira.jaspersoft.com/browse/JM-2341)
Jira issue [JM-2362](http://jira.jaspersoft.com/browse/JM-2362)
=> Fix: Schedule fixes

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/schedule/EditScheduleActivity.java, app/src/main/java/com/jaspersoft/android/jaspermobile/activities/schedule/NewScheduleActivity.java, app/src/main/res/values/constants.xml
Jira issue [JM-2355](http://jira.jaspersoft.com/browse/JM-2355)
=> Fix: Differentiate event for new and edit schedules

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/schedule/EditScheduleActivity.java
Jira issue [JM-2345](http://jira.jaspersoft.com/browse/JM-2345)
=> Fix: Changed edit schedule screen title

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/schedule/JobsFragment.java
Jira issue [JM-2346](http://jira.jaspersoft.com/browse/JM-2346)
=> Fix: Job changed is immediately reflected on jobs category

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/viewer/html/dashboard/BaseDashboardActivity.java, app/src/main/java/com/jaspersoft/android/jaspermobile/domain/interactor/AbstractUseCase.java, app/src/main/java/com/jaspersoft/android/jaspermobile/presentation/view/fragment/ReportViewFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/presentation/view/fragment/ReportVisualizeFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/print/DashboardPicturePrintJob.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/print/DashboardViewPrintJob.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/print/ReportPrintJob.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/print/ResourcePrintJob.java
Jira issue [JM-2367](http://jira.jaspersoft.com/browse/JM-2367)
=> Fix: Show printing as soon as report ready

app/src/dev/AndroidManifest.xml, app/src/dev/java/com/jaspersoft/android/jaspermobile/UtilReceiver.java, app/src/main/java/com/jaspersoft/android/jaspermobile/data/RealJasperRestClient.java, app/src/main/java/com/jaspersoft/android/jaspermobile/dialog/PasswordDialogFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/domain/AppCredentials.java
Jira Issue [JM-2367](http://jira.jaspersoft.com/browse/JM-2367)
=> Fix: Password dialog rotation issue

app/src/main/java/com/jaspersoft/android/jaspermobile/data/ComponentManager.java, app/src/main/java/com/jaspersoft/android/jaspermobile/presentation/contract/AuthenticationContract.java, app/src/main/java/com/jaspersoft/android/jaspermobile/presentation/page/AuthPageState.java, app/src/main/java/com/jaspersoft/android/jaspermobile/presentation/presenter/AuthenticationPresenter.java, app/src/main/java/com/jaspersoft/android/jaspermobile/presentation/view/activity/AuthenticatorActivity.java, app/src/main/java/com/jaspersoft/android/jaspermobile/presentation/view/fragment/AuthenticatorFragment.java, app/src/main/res/layout/activity_authentication.xml, app/src/test/java/com/jaspersoft/android/jaspermobile/data/ComponentManagerTest.java, app/src/test/java/com/jaspersoft/android/jaspermobile/presentation/presenter/ReportViewPresenterTest.java
Jira Issue [JM-2365](http://jira.jaspersoft.com/browse/JM-2365)
Jira Issue [JM-2370](http://jira.jaspersoft.com/browse/JM-2370)
Jira Issue [JM-2373](http://jira.jaspersoft.com/browse/JM-2373)
Jira Issue [JM-2375](http://jira.jaspersoft.com/browse/JM-2375)
=> Fix: Accounts form issues

app/src/main/java/com/jaspersoft/android/jaspermobile/dialog/BaseDialogFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/dialog/PasswordDialogFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/dialog/ValueInputDialogFragment.java
Jira Issue [JM-2364](http://jira.jaspersoft.com/browse/JM-2364)
=> Fix: sort dialog rotate crash

app/src/main/java/com/jaspersoft/android/jaspermobile/network/RequestExceptionHandler.java, app/src/main/res/values/strings.xml
Jira Issue [JM-2371](http://jira.jaspersoft.com/browse/JM-2371)
=> Fix: Handle job error length for label|output name

app/src/main/java/com/jaspersoft/android/jaspermobile/presentation/contract/RestReportContract.java, app/src/main/java/com/jaspersoft/android/jaspermobile/presentation/presenter/ReportViewPresenter.java, app/src/main/java/com/jaspersoft/android/jaspermobile/presentation/presenter/ReportVisualizePresenter.java, app/src/main/java/com/jaspersoft/android/jaspermobile/presentation/view/fragment/ReportViewFragment.java
Jira Issue [JM-2376](http://jira.jaspersoft.com/browse/JM-2376)
=> Fix: Empty page on first run fo report

app/src/main/java/com/jaspersoft/android/jaspermobile/dialog/ValueInputDialogFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/SavedItemHelper.java
Jira Issue [JM-2368](http://jira.jaspersoft.com/browse/JM-2368)
Jira Issue [JM-2325](http://jira.jaspersoft.com/browse/JM-2325)
=> Fix: Now user can remove incorrectly saved files

app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml
Jira Issue [JM-2374](http://jira.jaspersoft.com/browse/JM-2374)
Jira Issue [JM-2369](http://jira.jaspersoft.com/browse/JM-2369)
=> Fix: Updated copyright and http error strings

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/inputcontrols/InputControlsActivity.java, app/src/main/java/com/jaspersoft/android/jaspermobile/presentation/model/visualize/ErrorEvent.java, app/src/main/java/com/jaspersoft/android/jaspermobile/presentation/presenter/ReportVisualizePresenter.java, app/src/main/java/com/jaspersoft/android/jaspermobile/presentation/view/fragment/ReportViewFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/presentation/view/fragment/ReportVisualizeFragment.java
Jira Issue [JM-2377](http://jira.jaspersoft.com/browse/JM-2377)
Jira Issue [JM-2380](http://jira.jaspersoft.com/browse/JM-2380)
Jira Issue [JM-2382](http://jira.jaspersoft.com/browse/JM-2382)
=> Fix: Crashes on Dashboard Controls/Report Printing

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/info/fragments/SavedItemInfoFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/dialog/BaseDialogFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/dialog/RenameDialogFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/SavedItemHelper.java
Jira Issue [JM-2388](http://jira.jaspersoft.com/browse/JM-2388)
Jira Issue [JM-2389](http://jira.jaspersoft.com/browse/JM-2389)
Jira Issue [JM-2391](http://jira.jaspersoft.com/browse/JM-2391)
=> Fix: Fixed problem with dialogs callback after rotate

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/inputcontrols/InputControlsActivity.java
Jira issue [JM-2392](http://jira.jaspersoft.com/browse/JM-2392)
=> Fix dashboards report option issue

app/src/main/java/com/jaspersoft/android/jaspermobile/data/ComponentManager.java, app/src/main/java/com/jaspersoft/android/jaspermobile/presentation/presenter/NavigationPresenter.java, app/src/main/java/com/jaspersoft/android/jaspermobile/webview/report/bridge/ReportWebInterface.java, app/src/test/java/com/jaspersoft/android/jaspermobile/data/ComponentManagerTest.java, app/src/test/java/com/jaspersoft/android/jaspermobile/presentation/presenter/NavigationPresenterTest.java
Jira issue [JM-2396](http://jira.jaspersoft.com/browse/JM-2396)
=> Fix profile reloading while activity restores

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/library/LibraryPageFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/network/RequestExceptionHandler.java, app/src/main/res/values/strings.xml
Jira issue [JM-2406](http://jira.jaspersoft.com/browse/JM-2406)
=> Fix: Voice command button is hidden when menu is opened now. Errors for saved values

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/viewer/html/report/ReportCastActivity.java
Jira issue [JM-2401](http://jira.jaspersoft.com/browse/JM-2401)
=> Fix: Added page select dialog for report casting

app/src/main/java/com/jaspersoft/android/jaspermobile/presentation/view/activity/ReportVisualizeActivity.java
Jira issue [JM-2399](http://jira.jaspersoft.com/browse/JM-2399)
=> Fix: Added cast button for report viewer

app/src/main/java/com/jaspersoft/android/jaspermobile/data/ComponentManager.java
Jira issue [JM-2400](http://jira.jaspersoft.com/browse/JM-2400)
=> Fix: Cast is stopping on active account change

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/inputcontrols/InputControlsActivity.java
Jira issue [JM-2408](http://jira.jaspersoft.com/browse/JM-2408)
=> Fix: Report option progress bar persistence on cancle event

app/src/main/java/com/jaspersoft/android/jaspermobile/presentation/presenter/ReportViewPresenter.java
Jira issue [JM-2410](http://jira.jaspersoft.com/browse/JM-2410)
=> Fix: Fixed crash on rotating device while report still executing

app/src/main/java/com/jaspersoft/android/jaspermobile/data/cache/report/InMemoryReportPageCache.java, app/src/main/java/com/jaspersoft/android/jaspermobile/data/cache/report/ReportPageCache.java, app/src/main/java/com/jaspersoft/android/jaspermobile/data/repository/report/InMemoryReportRepository.java, app/src/test/java/com/jaspersoft/android/jaspermobile/data/cache/report/InMemoryReportPageCacheTest.java, app/src/test/java/com/jaspersoft/android/jaspermobile/data/repository/InMemoryReportRepositoryTest.java
Jira issue [JM-2411](http://jira.jaspersoft.com/browse/JM-2411)
=> Evict all report related page cache

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/storage/SavedReportsFragment.java
Jira issue [JM-2411](http://jira.jaspersoft.com/browse/JM-2411)
=> Fix: Reset sort type for saved items screen

app/src/main/java/com/jaspersoft/android/jaspermobile/data/repository/report/InMemoryReportRepository.java, app/src/main/java/com/jaspersoft/android/jaspermobile/presentation/contract/RestReportContract.java, app/src/main/java/com/jaspersoft/android/jaspermobile/presentation/page/ReportPageState.java, app/src/main/java/com/jaspersoft/android/jaspermobile/presentation/presenter/ReportViewPresenter.java, app/src/main/java/com/jaspersoft/android/jaspermobile/presentation/view/fragment/ReportViewFragment.java, app/src/test/java/com/jaspersoft/android/jaspermobile/presentation/presenter/ReportViewPresenterTest.java
Jira issue [JM-2411](http://jira.jaspersoft.com/browse/JM-2411)
=> Fix: Load issues for JRS 5.5

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/schedule/ScheduleFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/util/schedule/ScheduleViewModel.java
Jira issue [JM-2417](http://jira.jaspersoft.com/browse/JM-2417)
=> Fix: Fixed problem with resetting fire date on clicking run immediately

app/src/main/java/com/jaspersoft/android/jaspermobile/presentation/view/fragment/AuthenticatorFragment.java
Jira issue [JM-2416](http://jira.jaspersoft.com/browse/JM-2416)
=> Fix: Manually clear error on text input for auth fragment

app/src/main/java/com/jaspersoft/android/jaspermobile/presentation/view/activity/CastActivity.java
Jira issue [JM-2419](http://jira.jaspersoft.com/browse/JM-2419)
=> Fix: Cast button id hidden for server less than 6.0 or CE

app/src/main/java/com/jaspersoft/android/jaspermobile/activities/inputcontrols/InputControlsActivity.java
Jira Issue [JM-2423](http://jira.jaspersoft.com/browse/JM-2423)
=> Fix: Crash for report option reset on CE

app/build.gradle, app/lint.xml, app/src/main/java/com/jaspersoft/android/jaspermobile/data/ComponentManager.java, app/src/main/java/com/jaspersoft/android/jaspermobile/internal/di/modules/app/AppModule.java, app/src/main/java/com/jaspersoft/android/jaspermobile/presentation/view/component/ProfileActivationListener.java, app/src/test/java/com/jaspersoft/android/jaspermobile/data/ComponentManagerTest.java, app/src/test/java/com/jaspersoft/android/jaspermobile/data/cache/AccountJasperServerCacheTest.java, app/src/test/java/com/jaspersoft/android/jaspermobile/data/entity/mapper/JasperServerMapperTest.java, app/src/test/java/com/jaspersoft/android/jaspermobile/data/repository/InMemoryControlsRepositoryTest.java, app/src/test/java/com/jaspersoft/android/jaspermobile/data/repository/InMemoryReportRepositoryTest.java, app/src/test/java/com/jaspersoft/android/jaspermobile/domain/interactor/report/GetReportMetadataCaseTest.java, app/src/test/java/com/jaspersoft/android/jaspermobile/presentation/presenter/FakeGetReportShowControlsPropertyCase.java, app/src/test/java/com/jaspersoft/android/jaspermobile/presentation/presenter/ReportViewPresenterTest.java, app/src/test/java/com/jaspersoft/android/jaspermobile/presentation/presenter/ReportVisualizePresenterTest.java, app/src/test/java/com/jaspersoft/android/jaspermobile/presentation/presenter/StartupPresenterTest.java, build.gradle
Update SDK from snapshot to release
Enable lint checks
Fix broken tests
=> Clean up for release 2.3

app/src/main/java/com/jaspersoft/android/jaspermobile/network/cookie/AppCookieStore.java, build.gradle
Jira Issue [JM-2450](http://jira.jaspersoft.com/browse/JM-2450)
=> Fix: CSRF issue for webview cookie store

app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/constants.xml, app/src/main/res/values/strings.xml
Jira Issue [JM-2460](http://jira.jaspersoft.com/browse/JM-2460)
=> Add translations for App version 2.3

app/src/main/java/com/jaspersoft/android/jaspermobile/util/feedback/FeedbackSender.java, app/src/test/java/com/jaspersoft/android/jaspermobile/util/feedback/FeedbackSenderTest.java
Jira issue [JM-2414](http://jira.jaspersoft.com/browse/JM-2414)
=> Force only mail clients to receive feedback

app/src/main/java/com/jaspersoft/android/jaspermobile/JasperMobileApplication.java, app/src/main/java/com/jaspersoft/android/jaspermobile/data/ComponentManager.java, app/src/main/java/com/jaspersoft/android/jaspermobile/data/StateJasperClient.java, app/src/main/java/com/jaspersoft/android/jaspermobile/dialog/ProgressDialogFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/domain/JasperServer.java
Jira issue [JM-2569](http://jira.jaspersoft.com/browse/JM-2569)
=> Fix: Broken Graph Injection

app/src/main/java/com/jaspersoft/android/jaspermobile/dialog/ProgressDialogFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/ui/view/fragment/ReportViewFragment.java, app/src/main/java/com/jaspersoft/android/jaspermobile/ui/view/fragment/ReportVisualizeFragment.java
Jira issue [JM-2569](http://jira.jaspersoft.com/browse/JM-2569)
=> Fix: Progress rotation crash
